### PR TITLE
These fixes allow ember-cli-bourbon to be used as a Nested addon.

### PR DESCRIPTION
**Pull request by joedaniels29**
check out https://github.com/ember-cli/ember-cli/issues/3718 for a detailed error description for what happens currently without this patch.

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks @joedaniels29.

@rwjblue: in your opinion, is this the set of changes we should be making throughout the plugin ecosystem?

**Comment by rwjblue** [comment]
Seems like we need the bower directory, right?  If that is the only thing we need from `app` then we should get it from `this.project` which we have as `this.project.bowerDirectory`...

**Comment by lukemelia** [comment]
Thanks @rwjblue.

@joedaniels29 I appreciate your action on making ember-cli-bourbon "nesting-friendly". Do you want to revise your changes to use the approach @rwjblue outlined?

**Comment by rwjblue** [comment]
Now for the million dollar question: does it work this way? :smiling_imp:

**Comment by joedaniels29** [comment]
Yup! it seems to! I have the addon included from another addon and my app is running! Funny thing is, these types of quick fixes didnt seem to work for ember-cli-sass:
check out https://github.com/aexmachina/ember-cli-sass/issues/96

Anyways, thanks for input!

**Comment by lukemelia** [comment]
@joedaniels29 Thanks for revising. I think it is good to go. Can you squash this down to a single commit?

**Comment by joedaniels29** [comment]
Squashed!

**Comment by lukemelia** [comment]
Thanks @joedaniels29!

**Comment by lukemelia** [comment]
Released as 1.2.0

**Pull request merged**
