### PR TITLE
Update Ember CLI

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Is this going to be merged @lukemelia ?

**Comment by sohara** [comment]
@lukemelia Would be great to get this merged (particularly the bump to `broccoli-funnel`). Let me know if there's anything I can do to help :)

**Comment by lukemelia** [comment]
@sohara your reminder is a all it takes!

**Comment by sohara** [comment]
@lukemelia Thanks!

**Comment by lukemelia** [comment]
Published as 1.2.2. @sohara would you confirm it works as expected for you?

**Pull request merged**
